"""update users table

Revision ID: 44476a5cf1e8
Revises: 3d6eefe9aedb
Create Date: 2024-11-06 23:34:19.327071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44476a5cf1e8'
down_revision: Union[str, None] = '3d6eefe9aedb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
